import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const noInlineStyle =
  "Admin uses Tailwind classes; see docs/admin-design-brief.md §2.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Links and redirects must keep the visitor's language.
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "next/link",
              message: "Use Link from @/i18n/navigation.",
            },
            {
              name: "next/navigation",
              importNames: ["redirect", "usePathname", "useRouter"],
              message: "Use the version from @/i18n/navigation.",
            },
          ],
        },
      ],
    },
  },
  {
    // Admin is English only and has no locale provider, so it uses Next's
    // own Link and navigation, and must not use the locale-aware versions.
    files: ["app/admin/**", "components/admin/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/i18n/navigation",
              message:
                "Admin is English only: use next/link and next/navigation.",
            },
          ],
          patterns: [
            {
              group: ["next-intl", "next-intl/*"],
              message: "Admin is English only and has no locale provider.",
            },
          ],
        },
      ],
      // Admin is new code, so it starts without inline styles (#9): they
      // cannot use media queries or :hover. A value known only at run time
      // gets an eslint-disable-next-line comment saying why.
      "react/forbid-dom-props": [
        "error",
        { forbid: [{ propName: "style", message: noInlineStyle }] },
      ],
      "react/forbid-component-props": [
        "error",
        { forbid: [{ propName: "style", message: noInlineStyle }] },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by pnpm api:types; CI compares the raw output.
    "lib/api/schema.ts",
  ]),
]);

export default eslintConfig;
