// Generates lib/api/schema.ts from the API's openapi.yaml at the ref pinned
// in package.json (ADR-003). Run with `pnpm api:types`; CI runs it too and
// fails if the committed file differs.
import { readFileSync, writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const OUTPUT = "lib/api/schema.ts";

const { vetmimiApi } = JSON.parse(readFileSync("package.json", "utf8"));
const ref = vetmimiApi?.ref;
if (!ref) {
  console.error('package.json has no "vetmimiApi": { "ref": "…" }.');
  process.exit(1);
}

const url = `https://raw.githubusercontent.com/VetMiMi/vetmimi-api/${ref}/openapi.yaml`;

let spec;
try {
  const response = await fetch(url);
  if (response.status !== 200) {
    console.error(
      `Could not fetch openapi.yaml at ref ${ref}: HTTP ${response.status} from ${url}`,
    );
    process.exit(1);
  }
  spec = await response.text();
} catch (err) {
  console.error(
    `Could not fetch openapi.yaml at ref ${ref} from ${url}: ${err.cause?.message ?? err.message}`,
  );
  process.exit(1);
}

const ast = await openapiTS(spec);
const header = `// Generated by \`pnpm api:types\` from VetMiMi/vetmimi-api openapi.yaml at ${ref}. Do not edit.\n\n`;
writeFileSync(OUTPUT, header + astToString(ast));
console.log(`Wrote ${OUTPUT} from ${ref}.`);
